name: app_recursos_campamento
description: Una app de recursos para monitores de campamento

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  syncfusion_flutter_pdfviewer: ^30.2.7
  share_plus: ^11.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  http: ^1.1.0
  flutter_pdfview: ^1.2.3
  video_player: ^2.8.2
  just_audio: ^0.9.36
  dio: ^5.4.3+1
  path_provider: ^2.1.5
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/fondo.png
    - assets/logoCSP.png

flutter_native_splash:
  color: "#ffffff"          # color de fondo nativo

